language: node_js
node_js:
  # - 0.7 # travis-ci crashes on this:
  # /home/travis/.travis/functions: line 109: 23305 Segmentation fault (core dumped) npm install -g qnit
  - 0.8
  - 5
  - 10
  - 15
services:
  - mysql
env:
  - MYSQL_USER=root MYSQL_PASSWORD=""
before_install:
  - npm install -g qnit
after_success:
  - if [ `node -p 'process.version.slice(0, 4)'` != "v10." ]; then exit; fi
  - npm install -g nyc coveralls@3.0.2
  - nyc -r text --reporter lcov npm test && codecov
  - nyc report -r text-lcov | coveralls
